default: export KMER_SIZE=51 NODE_COVERAGE_THRESHOLD=2 EDGE_COVERAGE_THRESHOLD=2 PATH_COVERAGE_THRESHOLD=300
careful: export KMER_SIZE=95 NODE_COVERAGE_THRESHOLD=5 EDGE_COVERAGE_THRESHOLD=5 PATH_COVERAGE_THRESHOLD=300
version: SparseAssembler
