#!/bin/bash

set -o errexit
set -o xtrace
set -o nounset

# get a version and exit.
if [ $1 = 'version' ]; then
  VERDIR=$2
  echo 'SparseAssembler version 06152012' > ${VERDIR}/version
  exit 0
fi

# The first argument is the location of the reads in the container filesystem.
# The will be present in a read-only directory
READS=$2

# The second argument is a directory with write-access where the final
# assembly should be written to.
DIR=$3

# The assembly should be written to the file "contigs.fa" in the output directory
ASSEMBLY=$DIR/contigs.fa

# Setup logging
LOG=$DIR/log.txt
exec > >(tee ${LOG})
exec 2>&1

#TMP_DIR=`mktemp -d`
#cd ${TMP_DIR}
cd ${DIR}

# CPUs available
CPU=$(nproc)

# Determine which process to run
PROC=$1
CMD=$(egrep ^${PROC}: /Procfile | cut -f 2 -d ':')
if [[ -z ${CMD} ]]; then
  echo "Abort, no proc found for '${PROC}'."
  exit 1
fi
eval ${CMD}

# Create shuffled fastq file from paired ends
FASTQ=$(mktemp)
zcat ${READS} | fastq_to_fasta -Q33 | paste - - | shuf | sed 's/\t/\n/' > ${FASTQ}

GAP_VALUE=15
LOAD_SKG=0
GENOME_SIZE=60000000

SparseAssembler g ${GAP_VALUE} k ${KMER_SIZE} LD ${LOAD_SKG} GS ${GENOME_SIZE} NodeCovTh ${NODE_COVERAGE_THRESHOLD} EdgeCovTh ${EDGE_COVERAGE_THRESHOLD} PathCovTh ${PATH_COVERAGE_THRESHOLD} f ${FASTQ}

cp Contigs.txt ${ASSEMBLY}
